spring:
  data:
    mongodb:
      uri: mongodb://mongodb:27017/kidpass-auth-db

---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      host: mongodb # MongoDB host
      port: 27017 # MongoDB port
      database: kidpass # Database name
      username: admin # Username (if authentication is required)
      password: admin # Password (if authentication is required)

---
server:
  port: 8081

management:
  zipkin:
    tracing:
      enabled: false
  tracing:
    sampling:
      probability: 1.0
#  zipkin:
#    tracing:
#      endpoint: http://zipkin:9411/api/v2/spans

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
